### ISSUE TITLE
Update document title for product-detail page

### ISSUE THREAD

**Issue by supminn** [johnbabu021/shopping-cart#13]
**Is your feature request related to a problem? Please describe.**

Currently, the document is titled Dashboard, product-title, order. I would like to customize it as per the product names.

**Describe the solution you'd like**
Using the product title, I would add the changes into useEffect.

**Describe alternatives you've considered**

**Additional context**

**Comment by supminn** [comment]
I would like to work on improving this feature.

**Comment by johnbabu021** [comment]
okay you can work on that
thanks for contributoing
