### ISSUE TITLE
create a custom scroll bar

### ISSUE THREAD

**Issue by johnbabu021** [johnbabu021/shopping-cart#15]
scroll bar must be same width in the custom one 
color should be rgb(109, 40, 217)
background-color:white

**Comment by KarishmaVanwari** [comment]
Hey @johnbabu021 can I work on this issue as a part of Hacktoberfest 2021?

**Comment by johnbabu021** [comment]
yes ,it's on that
if you like to contribute let me know

**Comment by KarishmaVanwari** [comment]
> yes ,it's on that if you like to contribute let me know

Yup, I would like to work on it. Could you add the hacktoberfest label and assign me ?

**Comment by KarishmaVanwari** [comment]
@johnbabu021 have a look at #19
