### ISSUE TITLE
 Change State in cart and order page

### ISSUE THREAD

**Issue by johnbabu021** [johnbabu021/shopping-cart#3]
Use reducers instead of states

**Comment by kunalkumar007** [comment]
Let me try it.

**Comment by johnbabu021** [comment]
Okay thanks for contributing

**Comment by johnbabu021** [comment]
@kunalkumar007  is there any progress????

**Comment by kunalkumar007** [comment]
if you don't mind, can you give me a test user because I don't want to break any changes

**Comment by johnbabu021** [comment]
i don't get you
explain the problem you faced

**Comment by kunalkumar007** [comment]
I want to test the app on my own firebase app, can you provide me the details about the model or give me a test user credentials on your firebase app. 🙂
