### ISSUE TITLE
Image in readme

### ISSUE THREAD

**Issue by johnbabu021** [johnbabu021/shopping-cart#4]
The application has changed so take a screenshot and add it

**Comment by johnbabu021** [comment]
https://github.com/saviomartin/codehouse/blob/main/public/assets/codehouse.gif


Can make video not necessarily if you add image then you should change the background 
like desktop ui and other applications
Or take a screenshot of full screen

**Comment by priyanka010392** [comment]
@johnbabu021 could you please assign this to me, I would like to fix this.

**Comment by johnbabu021** [comment]
@priyanka010392  
thanks for contributing
