### ISSUE TITLE
Feature: I want to improve order page and want to add some cool buttons.

### ISSUE THREAD

**Issue by Himanshu-Agg12** [johnbabu021/shopping-cart#8]
@johnbabu021 assign me this task for making changes and also i can comment the code for better readability
I want to add more components for the shopping.

**Comment by johnbabu021** [comment]
Okay thanks for contributing

**Comment by johnbabu021** [comment]
is there any progress ????

**Comment by Himanshu-Agg12** [comment]
yes, please give some more time.

**Comment by johnbabu021** [comment]
okay let me check
thanks for contributing

**Comment by johnbabu021** [comment]
okay it's fine
